version: '3'
services:
  frontend:
    image: frontfibo:V1
    ports:
     - "3000:3000"
    build: ./frontend
  backend:
    build: ./backend
    ports:
     - "5000:5000"
    environment:
      MONGO_URI: mongodb://root:pass@:27017/
      LOGGING_LEVEL: INFO
    depends_on:
      - database
    volumes:
      - ./mongo-data:/data/db
  database:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: fibonacci_db
