name: Docker Image CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:  cd backend && docker build . --file Dockerfile --tag fibobackend:$(date +%Y%m%d-%H%M%S)

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: cd backend && docker push fibobackend:$(date +%Y%m%d-%H%M%S)








