name: Docker Frontend CI

on:
  push:
    paths:
      - 'frontend/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set timestamp variable
      run: echo "TIMESTAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

    - name: Build the Docker image
      run:  cd frontend && docker build . --file Dockerfile --tag ${{ secrets.REGISTRY_NAME }}/fibofrontend:$TIMESTAMP

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: cd frontend && docker push ${{ secrets.REGISTRY_NAME }}/fibofrontend:$TIMESTAMP
